services:
  pstream-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BACKEND_URL: ${VITE_BACKEND_URL}
        CORS_PROXY_URL: ${VITE_CORS_PROXY_URL}
        APP_DOMAIN: https://alphaflix.io.vn
        PWA_ENABLED: "true"
        OPENSEARCH_ENABLED: "true"
        TMDB_EMBED_API_URL: /tmdb-api
        ENABLE_DEVTOOLS_PROTECTION: ${VITE_ENABLE_DEVTOOLS_PROTECTION:-false}
    hostname: pstream-frontend
    expose:
      - '80'
    ports:
      - '4080:80'
    environment:
      - VIRTUAL_HOST=alphaflix.io.vn
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=alphaflix.io.vn
      - LETSENCRYPT_EMAIL=buiduccanh10@gmail.com
      - NGINX_PROXY_READ_TIMEOUT=30s
      - NGINX_PROXY_CONNECT_TIMEOUT=10s
      - NGINX_PROXY_SEND_TIMEOUT=30s
    env_file:
      - ${ENV_FILE_PATH:-.env}
    networks:
      - pstream-prod-network
      - betakiot_proxy_network
    restart: always


networks:
  pstream-prod-network:
    driver: bridge
  betakiot_proxy_network:
    external: true
