import { getTag } from "@sozialhelden/ietf-language-tags";
import { iso6393To1 } from "iso-639-3";

const languageAliases: Record<string, string> = {
  ar: "ar",
  ara: "ar",
  arabic: "ar",
  bg: "bg",
  bul: "bg",
  bulgarian: "bg",
  bn: "bn",
  ben: "bn",
  bengali: "bn",
  bs: "bs",
  bos: "bs",
  bosnian: "bs",
  ca: "ca",
  cat: "ca",
  catalan: "ca",
  cs: "cs",
  ces: "cs",
  cze: "cs",
  czech: "cs",
  da: "da",
  dan: "da",
  danish: "da",
  de: "de",
  ger: "de",
  deu: "de",
  german: "de",
  dutch: "nl",
  dut: "nl",
  nld: "nl",
  el: "el",
  ell: "el",
  gre: "el",
  greek: "el",
  en: "en",
  eng: "en",
  english: "en",
  es: "es",
  spa: "es",
  spanish: "es",
  "spanish latin america": "es-419",
  "spanish latin american": "es-419",
  "latin american spanish": "es-419",
  "spanish la": "es-419",
  et: "et",
  est: "et",
  estonian: "et",
  eu: "eu",
  eus: "eu",
  baq: "eu",
  basque: "eu",
  fa: "fa",
  fas: "fa",
  per: "fa",
  farsi: "fa",
  persian: "fa",
  "farsi persian": "fa",
  fi: "fi",
  fin: "fi",
  finnish: "fi",
  fil: "tl",
  filipino: "tl",
  fr: "fr",
  fre: "fr",
  fra: "fr",
  french: "fr",
  gl: "gl",
  glg: "gl",
  galician: "gl",
  he: "he",
  heb: "he",
  hebrew: "he",
  hi: "hi",
  hin: "hi",
  hindi: "hi",
  hr: "hr",
  hrv: "hr",
  scr: "hr",
  croatian: "hr",
  hu: "hu",
  hun: "hu",
  hungarian: "hu",
  hy: "hy",
  hye: "hy",
  arm: "hy",
  armenian: "hy",
  id: "id",
  ind: "id",
  indonesian: "id",
  is: "is",
  isl: "is",
  ice: "is",
  icelandic: "is",
  it: "it",
  ita: "it",
  italian: "it",
  ja: "ja",
  jpn: "ja",
  japanese: "ja",
  ka: "ka",
  kat: "ka",
  geo: "ka",
  georgian: "ka",
  km: "km",
  khm: "km",
  khmer: "km",
  cambodian: "km",
  kn: "kn",
  kan: "kn",
  kannada: "kn",
  ko: "ko",
  kor: "ko",
  korean: "ko",
  lo: "lo",
  lao: "lo",
  lt: "lt",
  lit: "lt",
  lithuanian: "lt",
  lv: "lv",
  lav: "lv",
  latvian: "lv",
  mk: "mk",
  mkd: "mk",
  mac: "mk",
  macedonian: "mk",
  ml: "ml",
  mal: "ml",
  malayalam: "ml",
  mn: "mn",
  mon: "mn",
  mongolian: "mn",
  mr: "mr",
  mar: "mr",
  marathi: "mr",
  ms: "ms",
  msa: "ms",
  may: "ms",
  malay: "ms",
  my: "my",
  mya: "my",
  bur: "my",
  burmese: "my",
  myanmar: "my",
  nl: "nl",
  norwegian: "no",
  nor: "no",
  no: "no",
  pa: "pa",
  pan: "pa",
  punjabi: "pa",
  pl: "pl",
  pol: "pl",
  polish: "pl",
  portuguese: "pt",
  por: "pt",
  pt: "pt",
  "brazilian portuguese": "pt-br",
  "portuguese br": "pt-br",
  "portuguese brazil": "pt-br",
  brazilian: "pt-br",
  pob: "pt-br",
  "pt-br": "pt-br",
  ro: "ro",
  ron: "ro",
  rum: "ro",
  romanian: "ro",
  ru: "ru",
  rus: "ru",
  russian: "ru",
  si: "si",
  sin: "si",
  sinhala: "si",
  sinhalese: "si",
  sk: "sk",
  slk: "sk",
  slo: "sk",
  slovak: "sk",
  sl: "sl",
  slv: "sl",
  slovene: "sl",
  slovenian: "sl",
  sq: "sq",
  sqi: "sq",
  alb: "sq",
  albanian: "sq",
  sr: "sr",
  srp: "sr",
  scc: "sr",
  serbian: "sr",
  sv: "sv",
  swe: "sv",
  swedish: "sv",
  ta: "ta",
  tam: "ta",
  tamil: "ta",
  te: "te",
  tel: "te",
  telugu: "te",
  th: "th",
  tha: "th",
  thai: "th",
  tl: "tl",
  tgl: "tl",
  tagalog: "tl",
  tr: "tr",
  tur: "tr",
  turkish: "tr",
  uk: "uk",
  ukr: "uk",
  ukrainian: "uk",
  ur: "ur",
  urd: "ur",
  urdu: "ur",
  vi: "vi",
  vie: "vi",
  vietnamese: "vi",
  "tieng viet": "vi",
  "tieng-viet": "vi",
  "tiếng việt": "vi",
  tiengviet: "vi",
  zh: "zh",
  zho: "zh",
  chi: "zh",
  chinese: "zh",
  "bilingual chinese": "zh",
  "chinese bilingual": "zh",
  "chinese simplified": "zh-cn",
  "simplified chinese": "zh-cn",
  "chinese traditional": "zh-tw",
  "traditional chinese": "zh-tw",
};

function normalizeLanguageLookupLabel(label: string): string {
  return label
    .trim()
    .toLowerCase()
    .replace(/[_/-]+/g, " ")
    .replace(/[()]+/g, " ")
    .replace(/\bbilingual\b/g, " ")
    .replace(/(?:[\s.-]+hi\d*)$/i, "")
    .replace(/\d+$/, "")
    .replace(/\s+/g, " ")
    .trim();
}

function normalizeLanguageCodeCandidate(label: string): string {
  return label
    .trim()
    .toLowerCase()
    .replace(/[_\s]+/g, "-")
    .replace(/[()]+/g, "")
    .replace(/(?:[.-]+hi\d*)$/i, "")
    .replace(/\d+$/, "")
    .replace(/-+/g, "-")
    .trim();
}

export function labelToLanguageCode(label?: string | null): string | null {
  if (!label) return null;

  const normalizedLabel = normalizeLanguageLookupLabel(label);
  if (!normalizedLabel) return null;

  if (languageAliases[normalizedLabel]) return languageAliases[normalizedLabel];

  const normalizedCode = normalizeLanguageCodeCandidate(label);
  if (!normalizedCode) return null;

  if (languageAliases[normalizedCode]) return languageAliases[normalizedCode];

  const fromIso6393 = iso6393To1[normalizedCode];
  if (fromIso6393) return fromIso6393;

  const tag = getTag(normalizedCode, true);
  if (tag?.language?.Description?.[0]) {
    return tag.parts.langtag ?? normalizedCode;
  }

  return null;
}
