const LANGUAGE_NAME_TO_CODE: Record<string, string> = {
  english: 'en',
  eng: 'en',
  en: 'en',
  vietnamese: 'vi',
  vie: 'vi',
  vi: 'vi',
  'tieng viet': 'vi',
  'tieng-viet': 'vi',
  'tiếng việt': 'vi',
  tiengviet: 'vi',
  french: 'fr',
  fre: 'fr',
  fra: 'fr',
  fr: 'fr',
  german: 'de',
  ger: 'de',
  deu: 'de',
  de: 'de',
  spanish: 'es',
  spa: 'es',
  es: 'es',
  'spanish (la)': 'es-419',
  'spanish (latin america)': 'es-419',
  spanish_latin_america: 'es-419',
  'spanish latin america': 'es-419',
  'latin american spanish': 'es-419',
  portuguese: 'pt',
  por: 'pt',
  pt: 'pt',
  'portuguese (br)': 'pt-br',
  'portuguese (brazil)': 'pt-br',
  'portuguese br': 'pt-br',
  'portuguese brazil': 'pt-br',
  brazilian_portuguese: 'pt-br',
  'brazilian portuguese': 'pt-br',
  brazilian: 'pt-br',
  pob: 'pt-br',
  'pt-br': 'pt-br',
  italian: 'it',
  ita: 'it',
  it: 'it',
  japanese: 'ja',
  jpn: 'ja',
  ja: 'ja',
  korean: 'ko',
  kor: 'ko',
  ko: 'ko',
  chinese: 'zh',
  zho: 'zh',
  chi: 'zh',
  zh: 'zh',
  'chinese (simplified)': 'zh-cn',
  'chinese (traditional)': 'zh-tw',
  chinese_simplified: 'zh-cn',
  chinese_traditional: 'zh-tw',
  'chinese simplified': 'zh-cn',
  'simplified chinese': 'zh-cn',
  'chinese traditional': 'zh-tw',
  'traditional chinese': 'zh-tw',
  thai: 'th',
  tha: 'th',
  th: 'th',
  indonesian: 'id',
  ind: 'id',
  id: 'id',
  russian: 'ru',
  rus: 'ru',
  ru: 'ru',
  dutch: 'nl',
  dut: 'nl',
  nld: 'nl',
  nl: 'nl',
  polish: 'pl',
  pol: 'pl',
  pl: 'pl',
  turkish: 'tr',
  tur: 'tr',
  tr: 'tr',
  swedish: 'sv',
  swe: 'sv',
  sv: 'sv',
  danish: 'da',
  dan: 'da',
  da: 'da',
  finnish: 'fi',
  fin: 'fi',
  fi: 'fi',
  norwegian: 'no',
  nor: 'no',
  no: 'no',
  arabic: 'ar',
  ara: 'ar',
  ar: 'ar',
  hindi: 'hi',
  hin: 'hi',
  hi: 'hi',
  bengali: 'bn',
  ben: 'bn',
  bn: 'bn',
  greek: 'el',
  ell: 'el',
  gre: 'el',
  el: 'el',
  hebrew: 'he',
  heb: 'he',
  he: 'he',
  hungarian: 'hu',
  hun: 'hu',
  hu: 'hu',
  czech: 'cs',
  ces: 'cs',
  cze: 'cs',
  cs: 'cs',
  romanian: 'ro',
  ron: 'ro',
  rum: 'ro',
  ro: 'ro',
  slovak: 'sk',
  slk: 'sk',
  slo: 'sk',
  sk: 'sk',
  slovenian: 'sl',
  slv: 'sl',
  sl: 'sl',
  serbian: 'sr',
  srp: 'sr',
  scc: 'sr',
  sr: 'sr',
  croatian: 'hr',
  hrv: 'hr',
  scr: 'hr',
  hr: 'hr',
  bosnian: 'bs',
  bos: 'bs',
  bs: 'bs',
  bulgarian: 'bg',
  bul: 'bg',
  bg: 'bg',
  ukrainian: 'uk',
  ukr: 'uk',
  uk: 'uk',
  estonian: 'et',
  est: 'et',
  et: 'et',
  latvian: 'lv',
  lav: 'lv',
  lv: 'lv',
  lithuanian: 'lt',
  lit: 'lt',
  lt: 'lt',
  farsi: 'fa',
  persian: 'fa',
  fas: 'fa',
  per: 'fa',
  fa: 'fa',
  farsi_persian: 'fa',
  malay: 'ms',
  msa: 'ms',
  may: 'ms',
  ms: 'ms',
  filipino: 'tl',
  tagalog: 'tl',
  tgl: 'tl',
  fil: 'tl',
  tl: 'tl',
  albanian: 'sq',
  sqi: 'sq',
  alb: 'sq',
  sq: 'sq',
  macedonian: 'mk',
  mkd: 'mk',
  mac: 'mk',
  mk: 'mk',
  icelandic: 'is',
  isl: 'is',
  ice: 'is',
  is: 'is',
  georgian: 'ka',
  kat: 'ka',
  geo: 'ka',
  ka: 'ka',
  armenian: 'hy',
  hye: 'hy',
  arm: 'hy',
  hy: 'hy',
  catalan: 'ca',
  cat: 'ca',
  ca: 'ca',
  basque: 'eu',
  eus: 'eu',
  baq: 'eu',
  eu: 'eu',
  galician: 'gl',
  glg: 'gl',
  gl: 'gl',
  urdu: 'ur',
  urd: 'ur',
  ur: 'ur',
  tamil: 'ta',
  tam: 'ta',
  ta: 'ta',
  telugu: 'te',
  tel: 'te',
  te: 'te',
  malayalam: 'ml',
  mal: 'ml',
  ml: 'ml',
  kannada: 'kn',
  kan: 'kn',
  kn: 'kn',
  marathi: 'mr',
  mar: 'mr',
  mr: 'mr',
  punjabi: 'pa',
  pan: 'pa',
  pa: 'pa',
  gujarati: 'gu',
  guj: 'gu',
  gu: 'gu',
  sinhala: 'si',
  sin: 'si',
  sinhalese: 'si',
  si: 'si',
  burmese: 'my',
  mya: 'my',
  bur: 'my',
  myanmar: 'my',
  my: 'my',
  khmer: 'km',
  khm: 'km',
  cambodian: 'km',
  km: 'km',
  lao: 'lo',
  lao_lang: 'lo',
  lo: 'lo',
  mongolian: 'mn',
  mon: 'mn',
  mn: 'mn',
  kazakh: 'kk',
  kaz: 'kk',
  kk: 'kk',
  uzbek: 'uz',
  uzb: 'uz',
  uz: 'uz',
  azerbaijani: 'az',
  aze: 'az',
  az: 'az',
};

const COMMON_ISO_639_2_TO_1: Record<string, string> = {
  eng: 'en',
  vie: 'vi',
  fre: 'fr',
  fra: 'fr',
  ger: 'de',
  deu: 'de',
  spa: 'es',
  por: 'pt',
  pob: 'pt-br',
  ita: 'it',
  jpn: 'ja',
  kor: 'ko',
  zho: 'zh',
  chi: 'zh',
  tha: 'th',
  ind: 'id',
  rus: 'ru',
  dut: 'nl',
  nld: 'nl',
  pol: 'pl',
  tur: 'tr',
  swe: 'sv',
  dan: 'da',
  fin: 'fi',
  nor: 'no',
  ara: 'ar',
  hin: 'hi',
  ben: 'bn',
  ell: 'el',
  gre: 'el',
  heb: 'he',
  hun: 'hu',
  ces: 'cs',
  cze: 'cs',
  ron: 'ro',
  rum: 'ro',
  slk: 'sk',
  slo: 'sk',
  slv: 'sl',
  srp: 'sr',
  scc: 'sr',
  hrv: 'hr',
  scr: 'hr',
  bos: 'bs',
  bul: 'bg',
  ukr: 'uk',
  est: 'et',
  lav: 'lv',
  lit: 'lt',
  fas: 'fa',
  per: 'fa',
  msa: 'ms',
  may: 'ms',
  tgl: 'tl',
  fil: 'tl',
  sqi: 'sq',
  alb: 'sq',
  mkd: 'mk',
  mac: 'mk',
  isl: 'is',
  ice: 'is',
  kat: 'ka',
  geo: 'ka',
  hye: 'hy',
  arm: 'hy',
  cat: 'ca',
  eus: 'eu',
  baq: 'eu',
  glg: 'gl',
  urd: 'ur',
  tam: 'ta',
  tel: 'te',
  mal: 'ml',
  kan: 'kn',
  mar: 'mr',
  pan: 'pa',
  guj: 'gu',
  sin: 'si',
  mya: 'my',
  bur: 'my',
  khm: 'km',
  mon: 'mn',
  kaz: 'kk',
  uzb: 'uz',
  aze: 'az',
};

export function normalizeLanguageCode(input?: string | null): string {
  if (!input) return 'unknown';
  const raw = input.trim().toLowerCase();
  if (!raw) return 'unknown';

  if (LANGUAGE_NAME_TO_CODE[raw]) {
    return LANGUAGE_NAME_TO_CODE[raw];
  }

  const cleaned = raw
    .replace(/[_/-]+/g, ' ')
    .replace(/[()]+/g, ' ')
    .replace(/\s*hi\d*$/i, '')
    .replace(/\d+$/, '')
    .trim();

  if (cleaned && LANGUAGE_NAME_TO_CODE[cleaned]) {
    return LANGUAGE_NAME_TO_CODE[cleaned];
  }

  const hyphenated = cleaned.replace(/\s+/g, '-');
  if (hyphenated && LANGUAGE_NAME_TO_CODE[hyphenated]) {
    return LANGUAGE_NAME_TO_CODE[hyphenated];
  }

  if (COMMON_ISO_639_2_TO_1[raw] || COMMON_ISO_639_2_TO_1[cleaned]) {
    return COMMON_ISO_639_2_TO_1[raw] || COMMON_ISO_639_2_TO_1[cleaned];
  }

  // If input is e.g. "en-us" or "pt-br"
  if (/^[a-z]{2}(-[a-z0-9]{2,4})?$/.test(raw)) {
    return raw;
  }
  if (/^[a-z]{2}(-[a-z0-9]{2,4})?$/.test(hyphenated)) {
    return hyphenated;
  }

  return raw;
}
